### ISSUE TITLE
Process killed (likely out of memory)

### ISSUE THREAD

**Issue by mrp089** [stanford-rc/user-support#2]
Hi,

I'm trying to post-process a simulation on Sherlock. The process runs on a single core and requires about 16GB of RAM. Since our personal queue is restricted to 8GB/node, I tried to run the process on the login node.

While the process is reading the raw results (~ 5 min), I can see the memory slowly climbing up to 16GB. I can also see that there is enough free RAM on the login node. However, once the process has finished reading and writes to disk, it receives a kill signal before finishing writing. While it's writing to disk, I can see that RAM usage stays at 16GB.

Is there a ...
- way to find out what exactly killed the process?
- time/memory limit on Sherlock on the login node?
- better way to run this post-processing?

Thank you very much!
Martin

**Comment by markyoder** [comment]
Martin -

You probably should not admit in writing to have tried to run a compute job
on the Login node. As you will see written many times in the Sherlock
documentation, login nodes are not meant for computing. The job was
probably recognized as being compute-like (too much memory) and killed. I'm
going jump in ahead of a proper sys-admin and recommend that you run this
job on a compute node.

I'm a little confused by the 8GB limit. What partition are you running on,
and have you tried requesting more memory? You can submit the job to the
normal (default) queue, with a memory request, something like:
$ sbatch --ntasks=1 --mem=16gb {other options as you prefer} {job name}

mark


Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"If you bore me, you lose your soul (to me)..."
~belly

**Comment by mrp089** [comment]
Thanks!
