### ISSUE TITLE
Submitting low-priority jobs

### ISSUE THREAD

**Issue by mrp089** [stanford-rc/user-support#3]
Hi,

I have a couple of low-priority jobs that I want to submit to our lab's partition without disturbing the other users. Specifically, I want those jobs to run only if there is unused capacity and no one else in the queue. 

Right now, I submit all my jobs with "qos=normal". Are there other qos options or other ways to submit these low-priority jobs?

Thanks a lot!
Martin

**Comment by vsoch** [comment]
Hey Martin! I think that, for the most part, normal would do the trick, although I don't think it would necessarily put you lower than someone else using that setting. I think what you could try (although I've never done it) is using `--nice` to decrease the priority, e.g., see https://slurm.schedmd.com/sbatch.html:

> --nice[=adjustment]
>  Run the job with an adjusted scheduling priority within Slurm. With no adjustment value the scheduling priority is decreased by 100. A negative nice value increases the priority, otherwise decreases it. The adjustment range is +/- 2147483645. Only privileged users can specify a negative adjustment. 

So I think you could try a very high value to decrease your own priority. If it's just for your lab's resources, changing that value should do the trick. Do you want to give it a shot and update us here if it works?

**Comment by mrp089** [comment]
Thanks, @vsoch! Works great, other jobs can skip ahead in the queue.

I noticed I might still block the whole queue for the runtime (2d+) of the jobs. Since the jobs easily restart, is there a way to have short jobs (e.g. 1h runtime) being resubmitted continuously and automatically? That way, no one in the queue would have to wait for more than 1h to skip ahead of me.

**Comment by vsoch** [comment]
hey @mrp089 - happy good morning! I think you might want to check out the re-queue example here https://www.sherlock.stanford.edu/docs/user-guide/running-jobs/#example_1. For example, you would also add a time limit to your job, and then a signal at some number of seconds before it's finished, and at that time re-submit. Would that work? This advice comes your way from conversation between @zyzhang1992 and I - thank you @zyzhang1992 !

**Comment by markyoder** [comment]
Martin - If you are running a batch of very similar jobs, another approach is to write them as a job array and limit the number of concurrent instances. For example to run 100 jobs with index `0<= k < 100` and 10 concurrent jobs, `--array=0-99%10`. The drawback is that it won't automatically scale up to `N>10` simultaneous jobs, but it can be a good method to sort of 'trickle-run' a large set of jobs.

**Comment by mrp089** [comment]
Thank you @vsoch, @zyzhang1992, and @markyoder for your input! I decided to go for the re-queue example. Works like a charm!

**Comment by mrp089** [comment]
After some more testing, I have found another failure mode.

I have several re-queueing 2-node jobs with a runtime of 0.5h each. Another user has a 4-node job in the queue. Due to my automatically re-queueing jobs (with different end-times), there will never be resources for a job with more than 2 nodes.

Is there a way to control re-queueing based on current demand in the queue?

**Comment by mrp089** [comment]
> After some more testing, I have found another failure mode.
> 
> I have several re-queueing 2-node jobs with a runtime of 0.5h each. Another user has a 4-node job in the queue. Due to my automatically re-queueing jobs (with different end-times), there will never be resources for a job with more than 2 nodes.
> 
> Is there a way to control re-queueing based on current demand in the queue?

Turns out, this is actually a problem. Do you have an idea of how to solve this?

**Comment by markyoder** [comment]
Remember that there is a Fair Share algorithm that helps to mitigate this problem. At some point, it will hold your jobs so that the 4 node jobs can run -- and in fact, every time you run a job, you're burning points to make this happen. You can also use `squeue` or `sinfo` to estimate the load on the queue, but there is nothing exact about it, and I don't believe there are any automated solutions to this (aside from Fair Share, at the cluster level). Additionally, requesting the right amount of time will help the scheduler use resources efficiently.
